# Generated by Django 5.0.4 on 2024-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default=0,
                help_text="Введите дату производства продукта",
                verbose_name="Дата производства продукта",
            ),
            preserve_default=False,
        ),
    ]
