# Generated by Django 5.0.4 on 2024-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(help_text="Введите цену", verbose_name="Цена"),
        ),
    ]
